services:
  web-ui:
    image: ggmartinez/laravel:php-8.2-apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - SKIP_COMPOSER_INSTALL=false
      - SKIP_SEEDERS=true
      - SKIP_MIGRATIONS=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SITE_TITLE="Syslog Web"
    labels:
      - "traefik.http.routers.myapp.rule=Host(`example.com`)"  
      - "traefik.http.routers.myapp.entrypoints=websecure"
      - "traefik.http.services.myapp.loadbalancer.server.port=80" 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
