services:
  web-ui:
    image: ggmartinez/laravel:php-8.2-apache
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    environment:
      - SKIP_COMPOSER_INSTALL=false
      - SKIP_SEEDERS=true
      - SKIP_MIGRATIONS=false

      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=syslog
      - DB_USERNAME=syslog
      - DB_PASSWORD=syslog
      - SESSION_DRIVER=file
      - CACHE_STORE=file
      - SITE_TITLE="Syslog Web"

      - VIRTUAL_HOST=domain.com # Set your domain if using nginx-proxy
      - CERT_NAME=cert 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    expose:
      - 80


  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Uncomment to use nginx-proxy with own SSL Certificates
  # nginx-proxy:
  #   image: jwilder/nginx-proxy:alpine
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs/cert.key:/etc/nginx/certs/cert.key:ro
  #     - ./certs/cert.crt:/etc/nginx/certs/cert.crt:ro
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"



