services:
  web-ui:
    image: ggmartinez/laravel:php-8.2-apache
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - SKIP_COMPOSER_INSTALL=false
      - SKIP_SEEDERS=true
      - SKIP_MIGRATIONS=false
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
